### ISSUE TITLE
Web3Bridge Logo

### ISSUE THREAD

**Issue by jebitok-dev** [sorXCode/merkle-airdrop-starter-ERC721#2]
- In the front-end make a change to the Web3Bridge logo on the landing page with the one that has been [shared](https://drive.google.com/file/d/1TUAvEsG7k7WgBLTfZ4RHP8AqWWYKGNCJ/view?usp=sharing)

**Comment by sorXCode** [comment]
Issue resolved in [PR 17](https://github.com/sorXCode/merkle-airdrop-starter-ERC721/pull/17)
